### ISSUE TITLE
Robots.txt

### ISSUE THREAD

**Issue by ghost** [ebola-geonode/ebola_geonode#11]
We need a robots.txt file for better discovery and SEO.

Related Links:
http://docs.geonode.org/en/1.1/deploy/production.html#robot-exclusion-file

Exclude:
- [x] /account/
- [x] /activity/
- [x] /admin/
- [x] /autocomplete/
- [x] /avatar/
- [x] /catalogue/
- [x] /comments/
- [x] /docs/
- [x] /geoserver/
- [x] /groups/
- [x] /maploom/
- [x] /messages/
- [x] /people/
- [x] /proxy/
- [x] /ratings/
- [x] /security/
- [x] /services/
- [x] /social/
- [x] /static/
- [x] /upload/

**Comment by state-hiu** [comment]
File is at https://github.com/ebola-geonode/rogue_geonode/blob/ebola_geonode/geoshape/templates/robots.txt

**Comment by state-hiu** [comment]
Done.  Reopen if we need to add something.
