### ISSUE TITLE
Banner image appears twice with an horizontal scroll

### ISSUE THREAD

**Issue by vdeparday** [ebola-geonode/ebola_geonode#2]
On the home page, scroll to the right

**Comment by jj0hns0n** [comment]
Should be fixed with https://github.com/ebola-geonode/rogue_geonode/commit/c518ea0637a14428056a11f0e3b50efecd5da63d ... @state-hiu can you deploy.

**Comment by vdeparday** [comment]
Closed after upgrading to 2.4
