### ISSUE TITLE
Cache admin and other layers before launch

### ISSUE THREAD

**Issue by jj0hns0n** [ebola-geonode/ebola_geonode#26]
Make sure we cache these admin boundary layers before launch.

I already removed the fill on all of them, and will use the symbology that Ana passed along ASAP.

**Comment by state-hiu** [comment]
Do you mean cache through GeoWebCache?

**Comment by jj0hns0n** [comment]
Yes. Go in and kick off the seeding manually.

**Comment by state-hiu** [comment]
Okay, think we can hold off until a more public launch (or at least a few days).  The server should be able to handle it for now.
