### ISSUE TITLE
Group Members Page // Layout Bug with Managers

### ISSUE THREAD

**Issue by ghost** [ebola-geonode/ebola_geonode#27]
Looks like there are some issues with the layout of the list of group managers.  Could be issue with CSS or templates.  My guess is the templates.

![image](https://cloud.githubusercontent.com/assets/2079497/5072983/95f0c6b2-6e4c-11e4-8c55-6905b2b554bb.png)

**Comment by jj0hns0n** [comment]
fixe upstream
