### ISSUE TITLE
Health Facilities Schema

### ISSUE THREAD

**Issue by jj0hns0n** [ebola-geonode/ebola_geonode#28]
We need to have an agreed on schema for the health facilities to the symbology, labels etc an be consistent. @unmeerim (Darren) and Sam Libby worked on the one below.

When uploading a shapefile with this schema, the downloaded layer needs to keep the field sizes the same as specified and uploaded. Reference #19 

| Field Name | Type | Length | Precision |
| --- | --- | --- | --- |
| UNIT_CODE | Text | 15 |  |
| UNIT_NAME | Text | 50 |  |
| Status | Text | 20 |  |
| Place_Name | Text | 50 |  |
| ADM2_Name | Text | 30 |  |
| ADM1_Name | Text | 30 |  |
| Latitude | Double | 10 | 3 |
| Longitude | Double | 10 | 3 |
| Beds_Open | Short Integer | 5 |  |
| Beds_Plan | Short Integer | 5 |  |
| Plan_Open | Date |  |  |
| Supporting | Text | 50 |  |
| Comment | Text | 100 |  |
| Valid_Date | Date |  |  |
| Accuracy | Text | 50 |  |
| Cont_Name | Text | 50 |  |
| Cont_Email | Text | 50 |  |
| Cont_Phone | Text | 30 |  |

**Comment by state-hiu** [comment]
Let me know when you have a schema locked and I can create the schema.xsd file to enable dropdowns/etc in MapLoom.

**Comment by jj0hns0n** [comment]
Im not sure anyone is going to edit directly in maploom. The key bit is that if @unmeerim uploads with this schema, and someone else downloads, that the schema is preserved. At the moment, the field lengths get made too long.

**Comment by jj0hns0n** [comment]
For reference, download this spreadsheet from HDX which has its own schema that is close to but not exactly like this. https://data.hdx.rwlabs.org/dataset/ebola-care-facilities-master-list

**Comment by jj0hns0n** [comment]
@unmeerim I think this is complete now?
