### ISSUE TITLE
Group Members Page // Pagination

### ISSUE THREAD

**Issue by ghost** [ebola-geonode/ebola_geonode#29]
Could we increase the "page size" for the members so it displays more than 4 out a time?  8 seems like a good number.

![image](https://cloud.githubusercontent.com/assets/2079497/5073041/1847ff68-6e4d-11e4-90aa-5215f876cf63.png)

**Comment by jj0hns0n** [comment]
Shouldn't this just scroll infinitely like everywhere else?

**Comment by state-hiu** [comment]
Or that.  Bug in upstream?

**Comment by jj0hns0n** [comment]
Fixed upstream
