### ISSUE TITLE
Download metadata does not appear in the layer detail page

### ISSUE THREAD

**Issue by vdeparday** [ebola-geonode/ebola_geonode#3]
![image](https://cloud.githubusercontent.com/assets/1036189/5040862/95af65da-6b83-11e4-89c2-8b615cf7460b.png)

**Comment by state-hiu** [comment]
Might be linked to https://github.com/GeoNode/geonode/pull/1609/files

Hotfix just swapping order of link.mime and link.name doesn't work.

**Comment by jj0hns0n** [comment]
I dont actually see any metadata links in the database. Am I missing something? @state-hiu lets discuss.

**Comment by jj0hns0n** [comment]
Confirmed this is not an issue in master

**Comment by vdeparday** [comment]
Can we hide the button as the workaround for now? and make sure the abstract is not truncated in the layer page and that #31 is fixed? Otherwise there is no way to see the medatata.

**Comment by jj0hns0n** [comment]
Hid this tab in https://github.com/ebola-geonode/rogue_geonode/commit/b9140d9036807c3e0e4d4ef9808d86a32f8e31c1

**Comment by vdeparday** [comment]
Solved by upgrading to 2.4
