### ISSUE TITLE
Enable monitoring of usage, download, etc...

### ISSUE THREAD

**Issue by vdeparday** [ebola-geonode/ebola_geonode#32]
Make sure Google Analytics and Django-requests are enabled and configured.

**Comment by jj0hns0n** [comment]
Which google account do we setup the google analytics in?

**Comment by vdeparday** [comment]
Sent you the infos in pm

**Comment by jj0hns0n** [comment]
Google analytics added here https://github.com/ebola-geonode/rogue_geonode/commit/0b6aacd8fd00c88729273f79093eff11a8ad6ff4 ... will wait on django-requests until redeploy to 2.4

**Comment by jj0hns0n** [comment]
Google Analytics is no receiving data. If you need access, ask @state-hiu or myself.

Will add django-requests when the 2.4b1 instance is up.

**Comment by state-hiu** [comment]
Google Analytics seems to be working.
