### ISSUE TITLE
MapLoom: Case Sensitivity in Table Filter

### ISSUE THREAD

**Issue by slibby** [ebola-geonode/ebola_geonode#47]
Is it possible to remove the case sensitivity in the "Filter" in the Table View? Having to get the Case right on the first try can lead to not-great UX.

**Comment by state-hiu** [comment]
@slibby are you referencing a feature in MapLoom (http://ebolageonode.org/maps/new) or GeoNode itself (http://ebolageonode.org/layers/?limit=100&offset=0)?  I thought case sensitivity was fixed in GeoNode, but it might require some more work (https://github.com/GeoNode/geonode/issues/1851).

**Comment by state-hiu** [comment]
Submitted issue upstream at https://github.com/ROGUE-JCTD/MapLoom/issues/120

Tracking upstream issues at https://github.com/ebola-geonode/ebola_geonode/issues/40
