### ISSUE TITLE
People page does not display on Chrome

### ISSUE THREAD

**Issue by vdeparday** [ebola-geonode/ebola_geonode#5]
This is fixed in 2.4 but not on this rogue deployment.

![image](https://cloud.githubusercontent.com/assets/1036189/5049633/1fc635d4-6bf5-11e4-864c-543845155867.png)

**Comment by jj0hns0n** [comment]
Confirmed this issue doesnt appear in master. Not sure what the fix is/was, but its no longer an issue in master.

**Comment by jj0hns0n** [comment]
I just hid this tab for now. The groups tab works and shows the list of people in that group. This is more important for now I think.

**Comment by jj0hns0n** [comment]
https://github.com/ebola-geonode/rogue_geonode/commit/b9140d9036807c3e0e4d4ef9808d86a32f8e31c1

**Comment by vdeparday** [comment]
Solved by upgrading to 2.4
